server {
    listen       80;
    server_name  localhost;

    root   /path/to/sky_takeout/front_end;
    index  index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    # 反向代理，处理管理端发送的请求
    location /api/ {
        proxy_pass http://localhost:8080/admin/;
    }

    # 反向代理，处理用户端发送的请求
    location /user/ {
        proxy_pass http://localhost:8080/user/;
    }

    # WebSocket
    location /ws/ {
        proxy_pass http://localhost:8080/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
